# Generated by Django 4.1.5 on 2023-01-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
